title: Space Finder
email: ""
description: >-
  Spacefinder includes detailed descriptions of spaces,
  filters based on space characteristics, and navigation
  via a map.
environment: production
baseurl: "/spacefinder-2"
url: "https://cambridge-collection.github.io"
host: "localhost"
google_analytics: ""
photo_dir: "/assets/photos/"
lang: "en"
dc:
  creator: ""
  dateCreated: ""
  dateModified: ""
  publisher: ""
  spatialCoverage: ""
  types:
    - "InteractiveResource"
  subjects:
    - "Digital mapping"
    - "College Campuses"
terms:
  url: ""
  text: ""
  shorttext: ""
foi:
  url: ""
  text: ""
  shorttext: ""
accessibility_statement:
  created: "12 June 2022"
  last_modified: "14 January 2023"
copyright: 
sass:
  style: compressed
plugins:
  - jekyll-feed
