name: concat-spacefinder-data
on: push
jobs:
  concat-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Concat space files and commit
        run: |
          cd main
          npm run concat
          git config --global user.name 'Spacefinder Bot'
          git config --global user.email '<>'
          git add --all
          git diff-index --quiet HEAD || (git commit -am "Workflow: Master space data file generated" && git push)